### ISSUE TITLE
Issues running painy following instructions on README

### ISSUE THREAD

**Issue by icaoberg** [lanesket/painy#2]
I followed the instructions.

Got the key and set up the variable
Used pip install (running in a conda environment with Python 3.10).

I get this error message

```
(base) ➜  painy comment 
 
Traceback (most recent call last):
  File "/home/icaoberg/miniconda3/bin/painy", line 8, in <module>
    sys.exit(main())
  File "/home/icaoberg/miniconda3/lib/python3.10/site-packages/painy/main.py", line 33, in main
    comment = get_comment(staged=staged)
  File "/home/icaoberg/miniconda3/lib/python3.10/site-packages/painy/comment.py", line 20, in get_comment
    valid_extensions = get_valid_extensions()
  File "/home/icaoberg/miniconda3/lib/python3.10/site-packages/painy/utils.py", line 7, in get_valid_extensions
    with open(os.path.join(get_package_path(), "p_extensions.txt")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/icaoberg/miniconda3/lib/python3.10/site-packages/painy/p_extensions.txt'
```

I will attempt to install from source.

**Comment by icaoberg** [comment]
Same issue installing from source. I can find the file is in the source code

```
(base) ➜  painy git:(main) find -type f -name "p_extensions.txt"
./painy/p_extensions.txt
```

so you might need to include the file in `setup.py`.

I cheated and manually added the missing text file to my local environment and works.

```
✗ painy comment
Changed files: ['setup.py']
Added package to setup.py for better installation.
```

BTW this project looks awesome can't wait to try it!

**Comment by lanesket** [comment]
@icaoberg Thank you for your Issue! Fixed it, you can now install the last version (at this moment - `0.1.4`) and you will not see this error again.
