### ISSUE TITLE
Issue using `openai` v1.6.1

### ISSUE THREAD

**Issue by icaoberg** [lanesket/painy#5]
```
(base) ➜  singularity-bowtie2 git:(main) ✗ painy comment     
Changed files: README.md
Traceback (most recent call last):
  File "/home/icaoberg/miniconda3/bin/painy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/icaoberg/miniconda3/lib/python3.11/site-packages/painy/main.py", line 97, in main
    msg = get_commmit_message(diff_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icaoberg/miniconda3/lib/python3.11/site-packages/painy/comment.py", line 44, in get_commmit_message
    response = model.get_response(prompt=diff_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icaoberg/miniconda3/lib/python3.11/site-packages/painy/chat.py", line 40, in get_response
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icaoberg/miniconda3/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

Issue with the latest version of `painy` using `openai` == 1.6.1.

**Comment by lanesket** [comment]
@icaoberg Yeah, the problem now there is no specified version in requirements.txt, I will add it soon, also I'll migrate it to `langchain` from my temporary solution. As a temporary solution please install `openai==0.28`, sorry for the confusion, it's a very small project that hasn't gotten a lot of attention.

**Comment by icaoberg** [comment]
@lanesket no biggies I realized this change in `openai` has affected many projects, not just yours. I will open a PR for your consideration.

This project is awesome. Don't short-sell-it.

![](https://media3.giphy.com/media/3Ur6pxVvpL0qq1OWbK/giphy.gif?cid=ecf05e4711vufqjkb4ag5i77cow5nk5v18fkkx62u8a6tza3&ep=v1_gifs_search&rid=giphy.gif&ct=g)

**Comment by lanesket** [comment]
@icaoberg I've migrated tool to `langchain` in order not to create my own solution based on OpenAI. Try it now, hope everything is solved.
